#!/bin/sh
#MISE description="Build container image (BUILDER=docker|podman)"
#MISE depends=["generate:*"]

BUILDER="${BUILDER:-docker}"
IMG="${IMG:-localhost:5001/dynamic-crd-watch:test}"

if [ "$BUILDER" = "docker" ]; then
  $BUILDER buildx build --load -t "$IMG" .
else
  $BUILDER build -t "$IMG" .
fi
