#!/bin/sh
#MISE description="Run tests (embedded apiserver, in-process manager)"
#MISE depends=["generate:*"]

KUBEBUILDER_ASSETS="$(setup-envtest use 1.31.0 -p path)" \
  go test ./... -coverprofile cover.out
